### ISSUE TITLE
ANNOUNCEMENT FOR EVERYONE: USE CROWDIN TO TRANSLATE!

### ISSUE THREAD

**Issue by LNLenost** [launchshopwii/wiiweb#24]
Hey everyone, with Fin's permission I set up a Crowdin to translate the website!
If the owner of NSC gives me permission I may set it up on the main website too.

Here's how it works:
1) Translate on https://crowdin.com/project/new-shop-channel-wiiweb for the language you want.
2) The edits get sent to my fork
3) I send a PR to Fin and he approves it (maybe)

That's it. Happy translating!

**Comment by trlandrew** [comment]
Yeah!

**Comment by LNLenost** [comment]
To edit the English files or create new ones: they HAVE TO BE INSIDE translations/en.

If not Crowdin wont work

**Comment by LNLenost** [comment]
WOO WE GOT A TRANSLATOR 🔥🔥🔥

**Comment by LNLenost** [comment]
I recreated the Crowdin btw. I deleted it 3 hours ago before of what seemed a shutdown but I recreated it.
