### ISSUE TITLE
Ermmm... what

### ISSUE THREAD

**Issue by LNLenost** [launchshopwii/wiiweb#41]
Yeah so idkwhereisthisname (the guy who sent the PR for translating error pages to italian) told me on GitHub abkut this being unarchived. What's going on? 💀💀

**Comment by LNLenost** [comment]
> Yeah so idkwhereisthisname (the guy who sent the PR for translating error pages to italian) told me on GitHub abkut this being unarchived. What's going on? 💀💀

**Comment by trlandrew** [comment]
nsc has shutdown

**Comment by LNLenost** [comment]
> nsc has shutdown

So what's this reviive thing?

**Comment by trlandrew** [comment]
also an wii shop channel revival I'm working on as a developer that actually has progress

https://ftolnks.xyz

**Comment by LNLenost** [comment]
> also an wii shop channel revival I'm working on as a developer that actually has progress
> 
> https://ftolnks.xyz

Wow, any way to collaborate? The github is private.

**Comment by trlandrew** [comment]
No idea

**Comment by LNLenost** [comment]
> No idea

K thx!

**Comment by trlandrew** [comment]
@LNLenost hey so this organization used to be for launchshop and it's back so I'll revive wiiweb u can help if u want to

**Comment by trlandrew** [comment]
(along with this report I'll be making the announcement bridge an actual thing)

**Comment by LNLenost** [comment]
> @LNLenost hey so this organization used to be for launchshop and it's back so I'll revive wiiweb u can help if u want to

YOOO tysm :D

**Comment by trlandrew** [comment]
> > @LNLenost hey so this organization used to be for launchshop and it's back so I'll revive wiiweb u can help if u want to
> 
> YOOO tysm :D

No problem, if you want to you can contact me via email since you don't have an Discord account, or via Twitter (which I use mostly because I rarely get anything in my inbox).

Also, an answer to your question*: no, NSC is not back, but LaunchShop is which will make stuff that was in NSC (although not really, no one worked there at all besides me) real, like as I said before: the announcement bridge and wiiweb.

If you want to learn more about LaunchShop, visit the main website [here](https://ls.ftolnks.xyz), the documentation link is [docs.ftolnks.xyz](https://docs.ftolnks.xyz).

**Comment by LNLenost** [comment]
Great! I'll probably use GitHub or email if it doesn't bother you.

DM me when LaunchShop start being developed and I'll help :)

**Comment by trlandrew** [comment]
LaunchShop is already being developed, but not wiiweb ATM. I'll send a comment on this issue once i start to work on wiiweb.

If you want to, here's my email: shitdapants@gmail.com

**Comment by LNLenost** [comment]
👍

I could also work on the main website

**Comment by trlandrew** [comment]
As a backend developer, no, unless you know PHP.

**Comment by LNLenost** [comment]
Not a lot.

**Comment by trlandrew** [comment]
Well then no. Honestly if you had a Discord it would be much easier to be able to talk to you, or just a Twitter. GitHub does not send me notifications.

**Comment by LNLenost** [comment]
Any news on the project?

**Comment by trlandrew** [comment]
no but soon (I'll probably delete this repo and make a new one)

**Comment by LNLenost** [comment]
Ok!

**Comment by LNLenost** [comment]
> no but soon (I'll probably delete this repo and make a new one)

Yo man, I made a discord account

Hit me up if u want (@lnlenost)

**Comment by LNLenost** [comment]
And after 1000 years, I have the honor to...

**Comment by LNLenost** [comment]
Close the issue.

**Comment by trlandrew** [comment]
And after 2 hours, I have the honor to...

**Comment by trlandrew** [comment]
Reopen this issue.

**Comment by LNLenost** [comment]
Nahh why 🙏😭

**Comment by LNLenost** [comment]
This is hands down the greatest comeback of all time (see general)

**Comment by trlandrew** [comment]
yes ive seen it anyway closing this issue

**Comment by idkwhere1sthisname** [comment]
lmfao 😭
